/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo3P;

/**
 *
 * @author Langas
 */
public class Prototipo3P extends javax.swing.JFrame {

    /**
     * Creates new form Prototipo3P
     */
    
    private MantenimientoAlumno ventanaAlumno;
    private MantenimientoAula ventanaAula;
    private MantenimientoCarrera ventanaCarrera;
    private MantenimientoCurso ventanaCurso;
    private MantenimientoFacultad ventanaFacultad;
    private MantenimientoJornada ventanaJornada;
    private MantenimientoMaestro ventanaMaestro;
    private MantenimientoSeccion ventanaSeccion;
    private MantenimientoSede ventanaSede;
    private AsignacionCA ventanaAsignacion;
    private AsignacionCM ventanaAsignacionM;
    
    public Prototipo3P() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Mfacultades = new javax.swing.JMenuItem();
        MMaestros = new javax.swing.JMenuItem();
        MAlumnos = new javax.swing.JMenuItem();
        MCarreras = new javax.swing.JMenuItem();
        MCursos = new javax.swing.JMenuItem();
        MSecciones = new javax.swing.JMenuItem();
        MSedes = new javax.swing.JMenuItem();
        MAulas = new javax.swing.JMenuItem();
        MJornadas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1317, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );

        jMenu8.setText("Bitacora Usuarios");

        jMenuItem4.setText("Usuarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuBar1.add(jMenu8);

        jMenu6.setText("Catalogos");

        Mfacultades.setText("Mantenimiento Facultades");
        Mfacultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfacultadesActionPerformed(evt);
            }
        });
        jMenu6.add(Mfacultades);

        MMaestros.setText("Mantenimiento Maestros");
        MMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMaestrosActionPerformed(evt);
            }
        });
        jMenu6.add(MMaestros);

        MAlumnos.setText("Mantenimiento Alumnos");
        MAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAlumnosActionPerformed(evt);
            }
        });
        jMenu6.add(MAlumnos);

        MCarreras.setText("Mantenimiento Carreras");
        MCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCarrerasActionPerformed(evt);
            }
        });
        jMenu6.add(MCarreras);

        MCursos.setText("Mantenimiento Cursos");
        MCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCursosActionPerformed(evt);
            }
        });
        jMenu6.add(MCursos);

        MSecciones.setText("Mantenimiento Secciones");
        MSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSeccionesActionPerformed(evt);
            }
        });
        jMenu6.add(MSecciones);

        MSedes.setText("Mantenimiento Sedes");
        MSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSedesActionPerformed(evt);
            }
        });
        jMenu6.add(MSedes);

        MAulas.setText("Mantenimiento Aulas");
        MAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAulasActionPerformed(evt);
            }
        });
        jMenu6.add(MAulas);

        MJornadas.setText("Mantenimiento Jornada");
        MJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MJornadasActionPerformed(evt);
            }
        });
        jMenu6.add(MJornadas);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Procesos");

        jMenuItem13.setText("Asignacion cursos a Alumnos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem1.setText("Asignacion cursos a Maestros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Josue Daniel Zapata Azañon 9959-18-4829");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

 
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MfacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfacultadesActionPerformed
        

        // TODO add your handling code here:
        ventanaFacultad = new MantenimientoFacultad();  
        jDesktopPane1.add(ventanaFacultad);
    }//GEN-LAST:event_MfacultadesActionPerformed

    private void MMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMaestrosActionPerformed
  
        // TODO add your handling code here:
        ventanaMaestro = new MantenimientoMaestro();  
        jDesktopPane1.add(ventanaMaestro);
    }//GEN-LAST:event_MMaestrosActionPerformed

    private void MAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAlumnosActionPerformed
    
        // TODO add your handling code here:
        ventanaAlumno = new MantenimientoAlumno();  
        jDesktopPane1.add(ventanaAlumno);
    }//GEN-LAST:event_MAlumnosActionPerformed

    private void MCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCarrerasActionPerformed
       

        // TODO add your handling code here:
        ventanaCarrera = new MantenimientoCarrera();  
        jDesktopPane1.add(ventanaCarrera);
    }//GEN-LAST:event_MCarrerasActionPerformed

    private void MCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCursosActionPerformed
      // TODO add your handling code here:
        ventanaCurso = new MantenimientoCurso();  
        jDesktopPane1.add(ventanaCurso);
    }//GEN-LAST:event_MCursosActionPerformed

    private void MSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSeccionesActionPerformed
        
        // TODO add your handling code here:
        ventanaSeccion = new MantenimientoSeccion();  
        jDesktopPane1.add(ventanaSeccion);
        
    }//GEN-LAST:event_MSeccionesActionPerformed

    private void MSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSedesActionPerformed
        // TODO add your handling code here:
        ventanaSede = new MantenimientoSede();  
        jDesktopPane1.add(ventanaSede);
    }//GEN-LAST:event_MSedesActionPerformed

    private void MAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAulasActionPerformed
       
        // TODO add your handling code here:
        ventanaAula = new MantenimientoAula();  
        jDesktopPane1.add(ventanaAula);
    }//GEN-LAST:event_MAulasActionPerformed

    private void MJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MJornadasActionPerformed
        
        // TODO add your handling code here:
        ventanaJornada = new MantenimientoJornada();  
        jDesktopPane1.add(ventanaJornada);
    }//GEN-LAST:event_MJornadasActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
            // TODO add your handling code here:
        ventanaAsignacion = new AsignacionCA();  
        jDesktopPane1.add(ventanaAsignacion);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

       

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prototipo3P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prototipo3P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prototipo3P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prototipo3P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prototipo3P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MAlumnos;
    private javax.swing.JMenuItem MAulas;
    private javax.swing.JMenuItem MCarreras;
    private javax.swing.JMenuItem MCursos;
    private javax.swing.JMenuItem MJornadas;
    private javax.swing.JMenuItem MMaestros;
    private javax.swing.JMenuItem MSecciones;
    private javax.swing.JMenuItem MSedes;
    private javax.swing.JMenuItem Mfacultades;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
